/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as CallIdRouteImport } from './routes/call.$id'
import { Route as IncomingIdRouteImport } from './routes/incoming.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const CallIdRoute = CallIdRouteImport.update({
  id: '/call/$id',
  path: '/call/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomingIdRoute = IncomingIdRouteImport.update({
  id: '/incoming/$id',
  path: '/incoming/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/join': typeof JoinRoute
  '/api/rtc': typeof ApiRtcRoute
  '/call/$id': typeof CallIdRoute
  '/incoming/$id': typeof IncomingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/join': typeof JoinRoute
  '/api/rtc': typeof ApiRtcRoute
  '/call/$id': typeof CallIdRoute
  '/incoming/$id': typeof IncomingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/join': typeof JoinRoute
  '/api/rtc': typeof ApiRtcRoute
  '/call/$id': typeof CallIdRoute
  '/incoming/$id': typeof IncomingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/feed' | '/join' | '/api/rtc' | '/call/$id' | '/incoming/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feed' | '/join' | '/api/rtc' | '/call/$id' | '/incoming/$id'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/join'
    | '/api/rtc'
    | '/call/$id'
    | '/incoming/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  JoinRoute: typeof JoinRoute
  ApiRtcRoute: typeof ApiRtcRoute
  CallIdRoute: typeof CallIdRoute
  IncomingIdRoute: typeof IncomingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$id': {
      id: '/call/$id'
      path: '/call/$id'
      fullPath: '/call/$id'
      preLoaderRoute: typeof CallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incoming/$id': {
      id: '/incoming/$id'
      path: '/incoming/$id'
      fullPath: '/incoming/$id'
      preLoaderRoute: typeof IncomingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  JoinRoute: JoinRoute,
  ApiRtcRoute: ApiRtcRoute,
  CallIdRoute: CallIdRoute,
  IncomingIdRoute: IncomingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
