/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiStripeRouteImport } from './routes/api/stripe'
import { Route as CallIdRouteImport } from './routes/call.$id'
import { Route as IncomingIdRouteImport } from './routes/incoming.$id'
import { Route as RateIdRouteImport } from './routes/rate.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeRoute = ApiStripeRouteImport.update({
  id: '/api/stripe',
  path: '/api/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const CallIdRoute = CallIdRouteImport.update({
  id: '/call/$id',
  path: '/call/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomingIdRoute = IncomingIdRouteImport.update({
  id: '/incoming/$id',
  path: '/incoming/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RateIdRoute = RateIdRouteImport.update({
  id: '/rate/$id',
  path: '/rate/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feed': typeof FeedRoute
  '/join': typeof JoinRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/stripe': typeof ApiStripeRoute
  '/call/$id': typeof CallIdRoute
  '/incoming/$id': typeof IncomingIdRoute
  '/rate/$id': typeof RateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feed': typeof FeedRoute
  '/join': typeof JoinRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/stripe': typeof ApiStripeRoute
  '/call/$id': typeof CallIdRoute
  '/incoming/$id': typeof IncomingIdRoute
  '/rate/$id': typeof RateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feed': typeof FeedRoute
  '/join': typeof JoinRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/stripe': typeof ApiStripeRoute
  '/call/$id': typeof CallIdRoute
  '/incoming/$id': typeof IncomingIdRoute
  '/rate/$id': typeof RateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/feed'
    | '/join'
    | '/reviews'
    | '/terms'
    | '/api/rtc'
    | '/api/stripe'
    | '/call/$id'
    | '/incoming/$id'
    | '/rate/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/feed'
    | '/join'
    | '/reviews'
    | '/terms'
    | '/api/rtc'
    | '/api/stripe'
    | '/call/$id'
    | '/incoming/$id'
    | '/rate/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/feed'
    | '/join'
    | '/reviews'
    | '/terms'
    | '/api/rtc'
    | '/api/stripe'
    | '/call/$id'
    | '/incoming/$id'
    | '/rate/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FeedRoute: typeof FeedRoute
  JoinRoute: typeof JoinRoute
  ReviewsRoute: typeof ReviewsRoute
  TermsRoute: typeof TermsRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiStripeRoute: typeof ApiStripeRoute
  CallIdRoute: typeof CallIdRoute
  IncomingIdRoute: typeof IncomingIdRoute
  RateIdRoute: typeof RateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe': {
      id: '/api/stripe'
      path: '/api/stripe'
      fullPath: '/api/stripe'
      preLoaderRoute: typeof ApiStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$id': {
      id: '/call/$id'
      path: '/call/$id'
      fullPath: '/call/$id'
      preLoaderRoute: typeof CallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incoming/$id': {
      id: '/incoming/$id'
      path: '/incoming/$id'
      fullPath: '/incoming/$id'
      preLoaderRoute: typeof IncomingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate/$id': {
      id: '/rate/$id'
      path: '/rate/$id'
      fullPath: '/rate/$id'
      preLoaderRoute: typeof RateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FeedRoute: FeedRoute,
  JoinRoute: JoinRoute,
  ReviewsRoute: ReviewsRoute,
  TermsRoute: TermsRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiStripeRoute: ApiStripeRoute,
  CallIdRoute: CallIdRoute,
  IncomingIdRoute: IncomingIdRoute,
  RateIdRoute: RateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
